#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "misskey"
name = "Misskey"
description.en = "Microblogging platform"
description.fr = "Platforme de Microblogging"

version = "2026.5.4~ynh2"

maintainers = []

[upstream]
license = "AGPL-3.0"
website = "https://misskey-hub.net/"
code = "https://github.com/misskey-dev/misskey"
cpe = "cpe:2.3:a:misskey:misskey"
fund = "https://patreon.com/syuilo"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = true

disk = "5G"
ram.build = "2G"
ram.runtime = "700M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, Misskey will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Misskey sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/misskey-dev/misskey/archive/refs/tags/2026.5.4.tar.gz"
    sha256 = "acd25a08f0d568449042207cfb102cea701f33a718d15713b1ebdcc072f20e1c"
    autoupdate.strategy = "latest_github_tag"

    [resources.sources.emojis]
    url = "https://github.com/misskey-dev/emojis/archive/73a6a754ade0fc419dbcdf1551f4446c45036021.tar.gz"
    sha256 = "9b93b96819ba7e8cff348cbdfb002dd82b898adf9233cf6bf45486297f7a33ef"
    autoupdate.upstream = "https://github.com/misskey-dev/emojis"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = [
        "ffmpeg",
        "postgresql",
        "redis-server"
    ]

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"
