#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

# Remove the dedicated systemd config
ynh_remove_systemd_config

# Remove the app-specific logrotate config
ynh_remove_logrotate

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# REMOVE THE REDIS DATABASE
#=================================================
ynh_script_progression --message="Removing the redis database..." --weight=1

ynh_redis_remove_db "$redis_db"

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing NodeJS..." --weight=1

# Remove metapackage and its dependencies
ynh_remove_nodejs

#=================================================
# REMOVE VARIOUS FILES
#=================================================

# Remove the log files

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
